import Head from 'next/head'
import Image from 'next/image'

export default function Home() {
  return (
    <>
      <Head>
        <title>Quicket Customer Account</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className='vw-section'>
          <div className='vw-section-header'>
            <h1 style={{ fontSize: "38px" }}>Get Started</h1>
            <p>Create your Quicket account</p>
          </div>
        </div>
      </main>
    </>
  )
}
